spring:
  profiles:
    active: local

logging:
  level:
    org.springframework.batch: DEBUG

---
spring:

  profiles: local

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/batchDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
     initialize-schema: always
    job:
      names: ${job.name:NONE}